### hello
GET http://127.0.0.1:11095/v1/changeawslightsailipsrv

### telnet
GET http://127.0.0.1:11095/v1/changeawslightsailipsrv/telnet/{ip}

### list available ip
GET http://127.0.0.1:11095/v1/changeawslightsailipsrv/ip

